### PR TITLE
Update 2023.html

### PR DESCRIPTION
**Pull request by gerlandotermini**
Adding my personal blog to the list. Thank you for organizing this event every year!

### CODE REVIEW

**Comment by arkhi** [comment]
Hello @gerlandotermini!

Do you mind updating your PR putting you on top of the list. It’s not crucial right now, but taking this habit will reduce conflicts in the foreseeable future. Imagine everyone committing on the same line. :)

Thank you!

**Comment by gerlandotermini** [comment]
Sure, of course. I wasn't sure if you were going in alphabetical order or what.

**Comment by gerlandotermini** [comment]
Thank you @arkhi ! Sorry for missing that in the readme. Maybe adding it also as an HTML comment right at the beginning of the list?

**Comment by arkhi** [comment]
That’s a jolly good idea; I’ll add this now. :+1: 

Thanks for your time and perspective. :)

**Pull request closed without merging**
