### PR TITLE
Wrap up 2024, silently prepare for 2025, improve usability (homepage link)

### PR DESCRIPTION
**Pull request by j9t**
Fairly simple PR to wrap up and prepare.

A site refactoring (maybe using Eleventy or some other SSG) would make all of this easier and less error-prone… maybe something to discuss in the next years :)

### CODE REVIEW

**Comment by arkhi** [comment]
Hello Jens,

I’ve had eleventy in mind for years but I’m not able to prioritise time to actually do it. So [all for it](https://github.com/css-naked-day/css-naked-day.github.io/issues/160), yes.

---

About adding anchors to titles. This troubles me as, semantically, this does not seem right to me:

* Titles are all linking to the home page when the title is actually not about the home page.
* Adding the anchor on the title of the  home page is redundant since we are on the home page already and the content of the page only changes when reloaded.
* We have a “Home” link that provides this navigation in the list on each page.

I know it’s an affordance to have a link on the `h1` in the case the title is stable across pages, which is not our case.

What do you think?

**Comment by j9t** [comment]
Hi @arkhi—do you want to move this into a review? Happy to respond here, too, though:

First, sorry for not providing extra context—this PR was thought to contain some quick fixes, not perfect solutions. We’ve been working on this site for some time so I had thought you could tell it was a quick iteration.

> About adding anchors to titles. This troubles me as, semantically, this does not seem right to me:
> 
> * Titles are all linking to the home page when the title is actually not about the home page.

See above, quick improvement. We could mitigate by just linking “CSS Naked Day” itself. It’s a compromise, but might better meet user expectations and also keep the scheme consistent.

> * Adding the anchor on the title of the  home page is redundant since we are on the home page already and the content of the page only changes when reloaded.

Absolutely. I opted for it because it’s consistently wrong on all pages. The “no links to active page” issue should be addressed in some future clean-up, but I opted against making it a concern in _this_ clean-up.

> * We have a “Home” link that provides this navigation in the list on each page.

Which breaks user expectations though—that link can’t even be considered part of some navigation. (I don’t consider it part of that, if you feel this is a “typical” spot for a homepage link. It really is the site logo or title normally.)

> I know it’s an affordance to have a link on the `h1` in the case the title is stable across pages, which is not our case.

I think you’re understanding the problem. As mentioned, perhaps another compromise could be to just link the “CSS Naked Day” part.

—By the way, I didn’t build the original website. There are many problems with it, but those should probably not be used against anyone who tries to improve the site.

**Comment by j9t** [comment]
Could you advise, @arkhi?

**Comment by j9t** [comment]
Reworked headings to strike balance between my suggestion to offer a more prominent, conventional home link and @arkhi’s concerns about linking the header, by only linking “CSS Naked Day.”

Merging given Fabien’s limited availability; will follow up on the respective email conversation.

**Pull request merged**
