### PR TITLE
add timezone clarification

### PR DESCRIPTION
**Pull request by alifeee**
I couldn't easily tell *which* 50 hours the "50 hours" referred to, so I put in a clarification.

GitHub has added the final space. I am unsure how to remove it.

### CODE REVIEW

**Comment by j9t** [comment]
@arkhi, do you like to review and comment on this?

**Comment by arkhi** [comment]
Hello!

I like the idea, thanks!

I think using only the range _00:00, April 9 UTC+14:00_ to _00:00, April 10 UTC-12:00_ is less euro-centric and more explicit.

**Comment by arkhi** [comment]
By this, I mean we could ditch the UTC+00:00 parts.

**Comment by alifeee** [comment]
I think

`from 10:00, April 8 UTC+00:00 (00:00, April 9 UTC+14:00), to 12:00, April 10 UTC+00:00 (00:00, April 10 UTC-12:00)`

...can be seen as euro-centric

I think

`from 00:00, April 9 UTC+14:00 (10:00, April 8 UTC+00:00), to 00:00, April 10 UTC-12:00 (12:00, April 10 UTC+00:00)`

...is more neutral.

I think `from "00:00, April 9 UTC+14:00" to "00:00, April 10 UTC-12:00"`

...doesn't provide enough information to be useful.

Those are my personal opinions.

**Comment by arkhi** [comment]
I prefer simplicity but don’t mind the details. With the flow being interrupted a lot, the _neutral version_ is extremely hard to read for me though. What do you think of this version?

```
from **00:00, April 9 UTC+14:00** to **00:00, April 10 UTC-12:00** (_10:00, April 8 UTC+00:00_ to _12:00, April 10 UTC+00:00_)
```

which would read “**00:00, April 9 UTC+14:00** to **00:00, April 10 UTC-12:00** (_10:00, April 8 UTC+00:00_ to _12:00, April 10 UTC+00:00_)”.

**Comment by alifeee** [comment]
new paragraph looks like 

image

I also think this paragraph probably belong above the [Don’t think, just strip](https://css-naked-day.github.io/#developers) section, but that is outside the scope of this PR.

**Review by arkhi — APPROVED** [review]
Here we go! Thank you @alifeee!

**Pull request merged**
