### PR TITLE
feat: add robots.txt

### PR DESCRIPTION
**Pull request by j9t**

### CODE REVIEW

**Review by arkhi — APPROVED** [review]
I’m not sure about the reason with telling agents to not index the website, but I see no objection.

Feel free to argument changes. :)

**Comment by arkhi** [comment]
> @arkhi, it’s just adding the file not for bots to run into nirvana. It’s not blocking anything—it’s rather confirming it’s all fair game.

I guess this bloop illustrates my interest for the topic on this website. :)

That triggers my curiosity though: What is the purpose of making the “Feel free to index anything” explicit since it would be the same without said file? Doesn’t it trigger more work in the end?

**Comment by j9t** [comment]
> That triggers my curiosity though: What is the purpose of making the “Feel free to index anything” explicit since it would be the same without said file? Doesn’t it trigger more work in the end?

Web crawlers usually look for robots.txt. Not having one leads to constantly returning 404s. Given regular traffic (much higher than for other text formats like ads.txt or security.txt), that seems unnecessary, and the work of setting up a two-line text file (that requires no further changes or maintenance) justified.

I’m not sure whether this satisfies you—first time I learn about objections about adding a robots.txt.

**Comment by arkhi** [comment]
There was no objection, just curiosity.

**Pull request merged**
